name: CI
on:
  push:
  pull_request:
    types: [ opened ]

jobs:
  next_version:
    name: ğŸ”– next version

    runs-on: ubuntu-latest
    container: docker://node:latest

    steps:
      - name: PR label
        uses: MECLab/find-pr-label-action@master
        with:
          match_any: "major|minor"

  build:
    name: ğŸ§± build

    runs-on: ubuntu-latest
    container: docker://node:latest

    steps:
      - uses: actions/checkout@v2

      # install dependencies
      - name: Install Dependencies
        run: npm ci

      - name: format
        run: make format

      - name: ğŸ§± Build Typescript src
        run: make build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: ./lib

  test:
    name: ğŸ§ª test

    runs-on: ubuntu-latest
    container: docker://node:latest

    steps:
      - uses: actions/checkout@v2

      # install dependencies
      - name: Install Dependencies
        run: npm ci

      # run tests
      - name: ğŸ§ª Run Unit Tests
        run: make test-unit

  package:
    name: ğŸ“¦ package

    runs-on: ubuntu-latest
    container: docker://node:buster

    needs: build

    steps:

      - uses: actions/checkout@v2.3.3

      - name: Download lib from build job
        uses: actions/download-artifact@v2
        with:
          name: lib
          path: ./lib

      # install dependencies
      - name: Install Dependencies
        run: npm ci

      - name: ğŸ§³ pack
        run: make package

      - name: ğŸ™ push distribution package
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .
          git diff-index --quiet HEAD || (git commit -m "ci: package distribution" && git push)